SOURCE_TYPE_FILE = "file"
SOURCE_TYPE_WEBSITE = "website"

STORAGE_TYPE_VECTOR = "vector"
STORAGE_TYPE_KEYWORD = "keyword"
STORAGE_TYPE_GRAPH = "graph"

KB_STATUS_PENDING = "pending"
KB_STATUS_EXTRACTING = "extracting"
KB_STATUS_CHUNKING = "chunking"
KB_STATUS_INDEXING = "indexing"
KB_STATUS_READY = "ready"
KB_STATUS_FAILED = "failed"

JOB_STATUS_RUNNING = "running"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"

DEFAULT_CHUNK_SIZE = 1024
DEFAULT_CHUNK_OVERLAP = 20
